name: Wildfly for Windup Web Console development

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  windup-wildfly4development:
    if: github.repository_owner == 'windup'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Windup Web project
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'
      - name: Package Wildfly for Windup Web Console development
        run: mvn -s settings.xml clean package -DskipTests -Pwindup-wildfly4development
      - name: Upload Wildfly for Windup Web Console development
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/windup-wildfly4development.zip
          overwrite: true
          tag: windup-wildfly4development
